runtime: python27
threadsafe: true

runtime_config:
  python_version: 2

instance_class: F1

libraries:
- name: ssl
  version: latest


handlers:
- url: /.*
  script: project_name.wsgi.application
  secure: always
