runtime: python
vm: true
entrypoint: gunicorn -b :$PORT project_name.wsgi
runtime_config:
  python_version: 3

service: py3-flexible

instance_class: F1

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
